clone_folder: c:\projects\w2m

install:
  - choco install --confirm libreoffice
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - gem install bundler --no-ri --no-rdoc
  - bundle install --jobs=3 --retry=3 --path=bundle
  - gem env

build_script:
  - gem build word-to-markdown.gemspec

test_script:
  - bundle exec rake test

environment:
  matrix:
    - ruby_version: "210"

artifacts:
  - path: install_log.txt
    name: install_log

cache:
  - bundle
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
  - C:/Ruby193/lib/ruby/gems/1.9.1
  - C:/Users/appveyor/.gem/ruby/1.9.1

build: false
